name: Build and deploy

on:
  push:
    # Sequence of patterns matched against refs/tags
    tags:
      - v*.*.*           # Push events to v1.0, v1.1, and v1.9 tags

permissions:
  contents: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "dir=$(yarn cache dir)" >> $GITHUB_OUTPUT

      - uses: actions/cache@v4
        id: yarn-cache # use this to check for `cache-hit` (`steps.yarn-cache.outputs.cache-hit != 'true'`)
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
      - run: yarn install
      - run: yarn build


      - run: cp -r dist/ui ./dist-ui
      - run: tar -cvzf dist-ui.tar.gz dist-ui
      - run: sha256sum dist-ui.tar.gz > dist-ui.tar.gz.sha256

      - name: GH Release
        uses: softprops/action-gh-release@v2
        with:
          prerelease: ${{ contains(github.ref, '-beat.') }}
          files: |
            dist-ui.tar.gz
            dist-ui.tar.gz.sha256        
